[package]
name = "evohime-eval"
version = "0.1.0"
publish = false
edition = "2021"

[[bin]]
name = "evohime-eval"
path = "src/main.rs"

[dependencies]
evohime-core = { path = "../evohime-core" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10"
thiserror = { workspace = true }
walkdir = "2"
