[package]
name = "evohime-cli"
version = "0.1.0"
publish = false
edition = "2021"

[[bin]]
name = "eva"
path = "src/main.rs"

[dependencies]
evohime-cli-contract = { path = "../evohime-cli-contract" }
evohime-cli-protocol = { path = "../evohime-cli-protocol" }
evohime-desktop-ipc = { path = "../desktop-ipc" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "rt", "time"] }
uuid = { version = "1", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
tokio = { workspace = true, features = ["net", "io-util", "macros", "rt", "time"] }
