use serde::{Deserialize,Serialize};use sha2::{Digest,Sha256};
pub const SCHEMA_VERSION:u32=1;const MAX_ITEMS:usize=256;
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum Availability{Available,Unavailable,Denied,Unknown}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum HandleKind{Child,WorkflowRun,BackgroundTask,Verification,Artifact,ContextResult,ApprovalPending}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum HandleStatus{Accepted,Running,Completed,Failed,Stale,Expired,Unknown}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct CapabilityEntry{pub stable_id:String,pub version:u64,pub callable_name:String,pub side_effect_class:String,pub risk_class:String,pub availability:Availability,pub descriptor_hash:String}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct Snapshot{pub schema_version:u32,pub id:String,pub kernel_id:String,pub run_id:String,pub grant_snapshot_ref:String,pub capability_entries:Vec<CapabilityEntry>,pub policy_hash:String,pub created_at_ms:i64,pub content_hash:String}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct Call{pub call_id:String,pub kernel_id:String,pub snapshot_ref:String,pub capability_id:String,pub capability_version:u64,pub args_ref:String,pub idempotency_key:String,pub content_hash:String}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct Handle{pub id:String,pub kind:HandleKind,pub owner_run_id:String,pub underlying_ref:String,pub status:HandleStatus,pub created_at_ms:i64,pub expires_at_ms:Option<i64>,pub content_hash:String}
#[derive(Debug,thiserror::Error,PartialEq,Eq)]pub enum KernelError{#[error("invalid kernel facade record: {0}")]Invalid(String),#[error("capability is not available in snapshot")]Unavailable}
fn hash<T:Serialize>(v:&T)->Result<String,KernelError>{serde_json::to_vec(v).map(|b|hex::encode(Sha256::digest(b))).map_err(|e|KernelError::Invalid(e.to_string()))}
pub fn validate_snapshot(s:&Snapshot)->Result<(),KernelError>{if s.schema_version!=SCHEMA_VERSION||s.id.trim().is_empty()||s.kernel_id.trim().is_empty()||s.run_id.trim().is_empty()||s.grant_snapshot_ref.trim().is_empty()||s.policy_hash.trim().is_empty()||s.created_at_ms<=0||s.capability_entries.len()>MAX_ITEMS{return Err(KernelError::Invalid("snapshot identity".into()))}let mut c=s.clone();c.content_hash.clear();if s.content_hash!=hash(&c)?{return Err(KernelError::Invalid("snapshot hash".into()))}Ok(())}
pub fn authorize_call(s:&Snapshot,c:&Call)->Result<(),KernelError>{validate_snapshot(s)?;if c.snapshot_ref!=s.id||c.kernel_id!=s.kernel_id{return Err(KernelError::Invalid("snapshot mismatch".into()))}let e=s.capability_entries.iter().find(|e|e.stable_id==c.capability_id&&e.version==c.capability_version).ok_or(KernelError::Unavailable)?;if e.availability!=Availability::Available{return Err(KernelError::Unavailable)}Ok(())}
