use serde::{Deserialize,Serialize}; use sha2::{Digest,Sha256};
pub const SCHEMA_VERSION:u32=1; const MAX_TEXT:usize=8192;
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum SourceKind{Bundled,GitRepository,LocalDirectory,WorkspaceDirectory,ImportedPackage,CompatibilitySource}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum InstallationMode{BundledManaged,ManagedSubscription,VendoredEditable,WorkspaceLocal,UserLocal,CompatibilityImported}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum UpdateState{Current,Checking,UpdateAvailable,StagedForReview,TrustReviewRequired,ReadyToActivate,LocallyModified,Diverged,MergeRequired,Conflict,Updating,UpdateFailed,Pinned,SourceUnavailable}
#[derive(Debug,Clone,Copy,Serialize,Deserialize,PartialEq,Eq)]#[serde(rename_all="snake_case")]pub enum DivergenceState{CleanAtBase,LocallyModified,UpstreamChanged,Diverged,MergeRequired,Conflict,Detached,Unknown}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct Source{pub schema_version:u32,pub id:String,pub kind:SourceKind,pub origin:String,pub requested_ref:Option<String>,pub resolver_ref:String,pub content_hash:String}
#[derive(Debug,Clone,Serialize,Deserialize,PartialEq,Eq)]pub struct Installed{pub installation_id:String,pub logical_skill_id:String,pub mode:InstallationMode,pub source_ref:String,pub installed_revision_ref:String,pub package_hash:String,pub local_content_hash:String,pub vendor_base_revision_ref:Option<String>,pub upstream_last_seen_revision_ref:Option<String>,pub update_state:UpdateState,pub divergence_state:DivergenceState,pub trust_record_ref:String,pub content_hash:String}
#[derive(Debug,thiserror::Error,PartialEq,Eq)]pub enum SkillLifecycleError{#[error("invalid skill lifecycle record: {0}")]Invalid(String),#[error("managed installation cannot be overwritten")]ManagedOverwriteDenied}
fn hash<T:Serialize>(v:&T)->Result<String,SkillLifecycleError>{serde_json::to_vec(v).map(|b|hex::encode(Sha256::digest(b))).map_err(|e|SkillLifecycleError::Invalid(e.to_string()))}
pub fn validate_source(s:&Source)->Result<(),SkillLifecycleError>{if s.schema_version!=SCHEMA_VERSION||s.id.trim().is_empty()||s.origin.len()>MAX_TEXT||s.resolver_ref.trim().is_empty(){return Err(SkillLifecycleError::Invalid("source identity".into()))}let mut c=s.clone();c.content_hash.clear();if s.content_hash!=hash(&c)?{return Err(SkillLifecycleError::Invalid("source hash".into()))}Ok(())}
pub fn validate_installation(i:&Installed)->Result<(),SkillLifecycleError>{if i.installation_id.trim().is_empty()||i.logical_skill_id.trim().is_empty()||i.source_ref.trim().is_empty()||i.installed_revision_ref.trim().is_empty()||i.package_hash.trim().is_empty()||i.local_content_hash.trim().is_empty(){return Err(SkillLifecycleError::Invalid("installation identity".into()))}if matches!(i.mode,InstallationMode::ManagedSubscription|InstallationMode::BundledManaged)&&matches!(i.divergence_state,DivergenceState::LocallyModified|DivergenceState::Diverged){return Err(SkillLifecycleError::Invalid("managed divergence".into()))}let mut c=i.clone();c.content_hash.clear();if i.content_hash!=hash(&c)?{return Err(SkillLifecycleError::Invalid("installation hash".into()))}Ok(())}
pub fn update_allowed(i:&Installed)->Result<(),SkillLifecycleError>{if matches!(i.mode,InstallationMode::VendoredEditable|InstallationMode::WorkspaceLocal|InstallationMode::UserLocal)&&matches!(i.divergence_state,DivergenceState::LocallyModified|DivergenceState::Diverged|DivergenceState::Conflict){return Err(SkillLifecycleError::ManagedOverwriteDenied)}Ok(())}
