import { useEffect, useState } from 'react'
import { useShellApi } from './shell-api'
import type { ConnectionState } from '@shared/api'
export function ComposableTerminationConditionsPanel({ connection, events }: { readonly connection: ConnectionState; readonly events: readonly { readonly eventType: string; readonly payload: string }[] }): React.JSX.Element {
  const api = useShellApi(); const [ownerScope, setOwnerScope] = useState(''); const [payload, setPayload] = useState(''); const [projection, setProjection] = useState<unknown>(null); const [message, setMessage] = useState('')
  useEffect(() => { const event = events.find((item) => item.eventType === 'composable_termination_conditions.result'); if (!event) return; try { setProjection(JSON.parse(event.payload)); setMessage('') } catch { setMessage('Core вернул некорректную termination projection.') } }, [events])
  const send = async (operation: 'validate_policy' | 'evaluate'): Promise<void> => { if (!api || connection !== 'connected' || !ownerScope.trim() || !payload.trim()) { setMessage('Нужны подключение, owner scope и bounded JSON payload.'); return }; const result = await api.invoke('core.composableTerminationConditions', { operation, ownerScope: ownerScope.trim(), payload: payload.trim(), idempotencyKey: crypto.randomUUID() }); if (!result.ok) setMessage(result.message) }
  return <section aria-label="Composable Termination Conditions"><h3>Composable Termination Conditions</h3><p>Условия, counters и первое решение принадлежат Core; continuation не переопределяет hard stop.</p><label>Owner scope <input value={ownerScope} onChange={(e) => setOwnerScope(e.target.value)} maxLength={128} /></label><label>Policy/state/event JSON <textarea value={payload} onChange={(e) => setPayload(e.target.value)} maxLength={512 * 1024} /></label><button type="button" onClick={() => void send('validate_policy')}>Проверить policy</button><button type="button" onClick={() => void send('evaluate')}>Оценить событие</button>{projection ? <pre>{JSON.stringify(projection, null, 2)}</pre> : null}{message ? <p role="status">{message}</p> : null}</section>
}
