import { useEffect, useState } from 'react'
import { useShellApi } from './shell-api'

type Projection = { status?: string; state?: string; protocol?: string; control_level?: string; auth_state?: string; capability_hash?: string; projection_json?: { contract_id?: string; contract_version?: number; preset_count?: number; active_runs?: number; active_run_count?: number; core_control_level?: string; raw_payload?: boolean; credentials?: string; auth_state?: string; capability_hash?: string; backend_class?: string }; error_code?: string }

export function ExternalCodingAgentAdapterPanel(): React.JSX.Element {
  const api = useShellApi(); const [projection, setProjection] = useState<Projection | null>(null)
  useEffect(() => { if (!api) return; const unsubscribe = api.subscribe((event) => { if (event.kind !== 'core-event' || !['external_coding_agent_adapter.result', 'agent_client_protocol_bridge.result'].includes(event.event.eventType)) return; try { setProjection(JSON.parse(event.event.payload) as Projection) } catch { setProjection({ status: 'invalid_projection' }) } }); void api.invoke('externalCodingAgentAdapter.status', { requestId: crypto.randomUUID(), ownerScope: 'external-coding-agent-adapter', idempotencyKey: crypto.randomUUID() }); void api.invoke('agentClientProtocolBridge.status', { requestId: crypto.randomUUID(), ownerScope: 'external-agent-acp', idempotencyKey: crypto.randomUUID() }); return unsubscribe }, [api])
  const meta = projection?.projection_json
  return <section className="panel" aria-label="External Coding Agent Adapter"><h2>Внешние coding-agent</h2><p role="status">Состояние: {projection?.state ?? 'ожидание Core'} · контроль: {projection?.control_level ?? meta?.core_control_level ?? 'unavailable'}</p><p>Протокол: {projection?.protocol ?? meta?.contract_id ?? 'нет'} · presets: {meta?.preset_count ?? 0} · активные run: {meta?.active_runs ?? meta?.active_run_count ?? 0}</p><p>ACP auth: {projection?.auth_state ?? meta?.auth_state ?? 'unknown'} · backend: {meta?.backend_class ?? 'external agent'} · capability hash: {projection?.capability_hash ?? meta?.capability_hash ?? 'нет'}</p><p>Credentials: только declared slots; raw payload: {meta?.raw_payload === false ? 'не передаётся' : 'запрещён'}. Opaque executor не считается fully approval controlled.</p>{projection && projection.status !== 'ok' && <p>Ошибка: {projection.error_code || projection.status}</p>}</section>
}
