import { useEffect, useState } from 'react'
import { useShellApi } from './shell-api'
import type { ConnectionState } from '@shared/api'

export function GuidedCalibrationSessionsPanel({ connection, events }: { readonly connection: ConnectionState; readonly events: readonly { readonly eventType: string; readonly payload: string }[] }): React.JSX.Element {
  const api = useShellApi(); const [id, setId] = useState(''); const [payload, setPayload] = useState(''); const [result, setResult] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { const event = events.find(item => item.eventType === 'guided_calibration_sessions.result'); if (event) setResult(event.payload) }, [events])
  const send = async (operation: 'create' | 'inspect' | 'replay' | 'iteration' | 'consolidate' | 'close'): Promise<void> => { if (!api || connection !== 'connected' || !id.trim() || (operation !== 'inspect' && operation !== 'replay' && !payload.trim())) { setMessage('Нужны подключение, session ID и bounded JSON.'); return }; const response = await api.invoke('core.guidedCalibrationSessions', { operation, sessionId: id.trim(), payload: payload.trim(), expectedVersion: 0, idempotencyKey: crypto.randomUUID() }); if (!response.ok) setMessage(response.message) }
  return <section aria-label="Guided Calibration Sessions"><h3>Guided Calibration Sessions</h3><p>Сессия хранит redacted feedback и hashes; подтверждённые кандидаты передаются только в Continual Refinement.</p><label>Session ID <input value={id} onChange={event => setId(event.target.value)} maxLength={128} /></label><label>Session/action JSON <textarea value={payload} onChange={event => setPayload(event.target.value)} maxLength={512 * 1024} /></label><div>{(['create', 'inspect', 'replay', 'iteration', 'consolidate', 'close'] as const).map(operation => <button key={operation} type="button" onClick={() => void send(operation)}>{operation}</button>)}</div>{result ? <pre>{result}</pre> : null}{message ? <p role="status">{message}</p> : null}</section>
}
