import { useEffect, useState } from 'react'
import { useShellApi } from './shell-api'
import type { ConnectionState } from '@shared/api'

export function SchemaDrivenAgentConfigurationPanel({ connection, events }: { readonly connection: ConnectionState; readonly events: readonly { readonly eventType: string; readonly payload: string }[] }): React.JSX.Element {
  const api = useShellApi(); const [scope, setScope] = useState('application'); const [values, setValues] = useState('{"reasoning_effort":"auto"}'); const [result, setResult] = useState<unknown>(null); const [message, setMessage] = useState('')
  useEffect(() => { const event = events.find((item) => item.eventType === 'schema_driven_agent_configuration.result'); if (!event) return; try { setResult(JSON.parse(event.payload)); setMessage('') } catch { setMessage('Core вернул некорректную configuration projection.') } }, [events])
  const send = async (operation: 'get_schema' | 'get_snapshot' | 'apply'): Promise<void> => { if (!api || connection !== 'connected') { setMessage('Нет подключения к Core.'); return }; if (operation === 'apply') { try { JSON.parse(values) } catch { setMessage('Values должны быть корректным JSON-объектом.'); return } }; const response = await api.invoke('core.schemaDrivenAgentConfiguration', { operation, scope, payload: operation === 'apply' ? JSON.stringify({ values: JSON.parse(values) }) : '', expectedRevision: 0, idempotencyKey: crypto.randomUUID() }); if (!response.ok) setMessage(response.message) }
  return <section aria-label="Schema-Driven Agent Configuration"><h3>Schema-Driven Configuration</h3><p>Допустимые настройки и effective snapshot определяет Core; secret fields показываются только как configured/not configured.</p><label>Scope <select value={scope} onChange={(event) => setScope(event.target.value)}><option value="application">Application defaults</option><option value="workspace">Workspace defaults</option><option value="agent">Agent profile</option><option value="conversation">Conversation defaults</option><option value="run">Run override</option></select></label><label>Values JSON <textarea value={values} onChange={(event) => setValues(event.target.value)} maxLength={256 * 1024} /></label><div><button type="button" onClick={() => void send('get_schema')}>Получить схему</button><button type="button" onClick={() => void send('get_snapshot')}>Получить snapshot</button><button type="button" onClick={() => void send('apply')}>Применить</button></div>{result ? <pre>{JSON.stringify(result, null, 2)}</pre> : null}{message ? <p role="status">{message}</p> : null}</section>
}
