import { useEffect, useState } from 'react'
import { useShellApi } from './shell-api'
import type { ConnectionState } from '@shared/api'

export function TaskWorktreeIsolationPanel({ connection, events }: { readonly connection: ConnectionState; readonly events: readonly { readonly eventType: string; readonly payload: string }[] }): React.JSX.Element {
  const api = useShellApi(); const [projectId, setProjectId] = useState(''); const [taskId, setTaskId] = useState(''); const [worktreeId, setWorktreeId] = useState(''); const [branch, setBranch] = useState('eva/task'); const [baseCommit, setBaseCommit] = useState('HEAD'); const [projection, setProjection] = useState<unknown>(null); const [message, setMessage] = useState('')
  useEffect(() => { const event = events.find((item) => item.eventType === 'task_worktree_isolation.result'); if (!event) return; try { setProjection(JSON.parse(event.payload)); setMessage('') } catch { setMessage('Core вернул некорректную projection.') } }, [events])
  const send = async (operation: 'create' | 'ready' | 'integrating' | 'cleanup_pending'): Promise<void> => { if (!api || connection !== 'connected' || !projectId.trim() || !taskId.trim() || !worktreeId.trim()) { setMessage('Нужны подключение, project ID, task ID и worktree ID.'); return }; const result = await api.invoke('core.taskWorktreeIsolation', { operation, projectId: projectId.trim(), taskId: taskId.trim(), worktreeId: worktreeId.trim(), branch: branch.trim(), baseCommit: baseCommit.trim(), expectedVersion: Number((projection as { version?: number } | null)?.version ?? 0), idempotencyKey: crypto.randomUUID() }); if (!result.ok) setMessage(result.message) }
  return <section aria-label="Task worktree isolation"><h3>Task Worktree Isolation</h3><p>Core хранит lifecycle и version fence; UI не выбирает host path и не выполняет Git effect напрямую.</p><label>Project ID <input value={projectId} onChange={(e) => setProjectId(e.target.value)} maxLength={128} /></label><label>Task ID <input value={taskId} onChange={(e) => setTaskId(e.target.value)} maxLength={128} /></label><label>Worktree ID <input value={worktreeId} onChange={(e) => setWorktreeId(e.target.value)} maxLength={128} /></label><label>Branch ref <input value={branch} onChange={(e) => setBranch(e.target.value)} maxLength={128} /></label><label>Base commit <input value={baseCommit} onChange={(e) => setBaseCommit(e.target.value)} maxLength={128} /></label><button type="button" onClick={() => void send('create')}>Создать registry</button><button type="button" onClick={() => void send('ready')}>Ready</button><button type="button" onClick={() => void send('cleanup_pending')}>Cleanup pending</button>{projection ? <pre>{JSON.stringify(projection, null, 2)}</pre> : null}{message ? <p role="status">{message}</p> : null}</section>
}
