import { useEffect, useState } from 'react'
import { useShellApi } from './shell-api'
import type { ConnectionState } from '@shared/api'

export function TeamCoordinationPoliciesPanel({ connection, events }: { readonly connection: ConnectionState; readonly events: readonly { readonly eventType: string; readonly payload: string }[] }): React.JSX.Element {
  const api = useShellApi(); const [teamId, setTeamId] = useState(''); const [payload, setPayload] = useState(''); const [result, setResult] = useState<unknown>(null); const [message, setMessage] = useState('')
  useEffect(() => { const event = events.find((item) => item.eventType === 'team_coordination_policies.result'); if (!event) return; try { setResult(JSON.parse(event.payload)); setMessage('') } catch { setMessage('Core вернул некорректную coordination projection.') } }, [events])
  const send = async (operation: 'validate_policy' | 'save_policy' | 'select' | 'save_state' | 'select_strategy'): Promise<void> => { if (!api || connection !== 'connected' || !teamId.trim() || !payload.trim()) { setMessage('Нужны подключение, team ID и bounded JSON payload.'); return }; const response = await api.invoke('core.teamCoordinationPolicies', { operation, teamId: teamId.trim(), payload: payload.trim(), expectedVersion: 0, idempotencyKey: crypto.randomUUID() }); if (!response.ok) setMessage(response.message) }
  return <section aria-label="Team Coordination Policies"><h3>Team Coordination Policies</h3><p>Core выбирает роль (typed participant) и причину решения; child grants, approvals, protocol routes и effects остаются в существующем runtime.</p><label>Team ID <input value={teamId} onChange={(event) => setTeamId(event.target.value)} maxLength={256} /></label><label>Team/spec/state JSON <textarea value={payload} onChange={(event) => setPayload(event.target.value)} maxLength={256 * 1024} /></label><div>{(['validate_policy', 'save_policy', 'select', 'save_state', 'select_strategy'] as const).map((operation) => <button key={operation} type="button" onClick={() => void send(operation)}>{operation}</button>)}</div>{result ? <pre>{JSON.stringify(result, null, 2)}</pre> : null}{message ? <p role="status">{message}</p> : null}</section>
}
