import { useEffect, useState } from 'react'
import { useShellApi } from './shell-api'
import type { ConnectionState } from '@shared/api'
export function TypedAgentHandoffContractPanel({ connection, events }: { readonly connection: ConnectionState; readonly events: readonly { readonly eventType: string; readonly payload: string }[] }): React.JSX.Element {
  const api = useShellApi(); const [handoffId, setHandoffId] = useState(''); const [packetJson, setPacketJson] = useState(''); const [actor, setActor] = useState(''); const [reason, setReason] = useState(''); const [result, setResult] = useState<unknown>(null); const [message, setMessage] = useState('')
  useEffect(() => { const event = events.find((item) => item.eventType === 'typed_agent_handoff_contract.result'); if (!event) return; try { setResult(JSON.parse(event.payload)); setMessage('') } catch { setMessage('Core вернул некорректную handoff projection.') } }, [events])
  const send = async (operation: 'propose' | 'transition' | 'get'): Promise<void> => { if (!api || connection !== 'connected' || !handoffId.trim() || !actor.trim() || !reason.trim() || (operation !== 'get' && !packetJson.trim())) { setMessage('Нужны подключение, handoff ID, actor/reason и bounded JSON.'); return }; const response = await api.invoke('core.typedAgentHandoffContract', { operation, handoffId: handoffId.trim(), packetJson: packetJson.trim(), actor: actor.trim(), reason: reason.trim(), expectedVersion: 1, idempotencyKey: crypto.randomUUID() }); if (!response.ok) setMessage(response.message) }
  return <section aria-label="Typed Agent Handoff Contract"><h3>Typed Agent Handoff</h3><p>Lifecycle ownership transfer с ACK/NACK; refs и context budget проверяются Core, capabilities не наследуются.</p><label>Handoff ID <input value={handoffId} onChange={(event) => setHandoffId(event.target.value)} maxLength={512} /></label><label>Actor <input value={actor} onChange={(event) => setActor(event.target.value)} maxLength={512} /></label><label>Reason <input value={reason} onChange={(event) => setReason(event.target.value)} maxLength={512} /></label><label>Packet JSON / next state JSON <textarea value={packetJson} onChange={(event) => setPacketJson(event.target.value)} maxLength={256 * 1024} /></label><div>{(['propose', 'transition', 'get'] as const).map((operation) => <button key={operation} type="button" onClick={() => void send(operation)}>{operation}</button>)}</div>{result ? <pre>{JSON.stringify(result, null, 2)}</pre> : null}{message ? <p role="status">{message}</p> : null}</section>
}
