[package]
name = "evohime-listener-audio"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
evohime-listener-contract = { path = "../evohime-listener-contract" }
thiserror = "2"

[target.'cfg(windows)'.dependencies]
cpal = "0.15"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Media_KernelStreaming", "Win32_System_LibraryLoader", "Win32_System_Memory", "Win32_UI_WindowsAndMessaging"] }

