/* eslint-disable */
/**
 * Generated from crates/server/src/routes.rs.
 * Do not edit by hand. Run: npm run generate:openapi
 */

export const openApiPaths = {
  "/health": ["get"] as const,
  "/openapi.json": ["get"] as const,
  "/api/auth/status": ["get"] as const,
  "/api/features": ["get"] as const,
  "/api/models/config": ["get","put"] as const,
  "/api/models/available": ["get"] as const,
  "/api/sessions": ["get","post"] as const,
  "/api/sessions/archived": ["get"] as const,
  "/api/sessions/:session_id": ["delete"] as const,
  "/api/sessions/:session_id/archive": ["post"] as const,
  "/api/sessions/:session_id/unarchive": ["post"] as const,
  "/api/sessions/:session_id/history": ["get"] as const,
  "/api/sessions/:session_id/attachments": ["get","post"] as const,
  "/api/auth/github": ["get"] as const,
  "/api/github/pull-requests": ["get","post"] as const,
  "/api/github/pull-requests/:number": ["get"] as const,
  "/api/files": ["get"] as const,
  "/api/projects": ["get","post"] as const,
  "/api/files/content": ["get","put","post"] as const,
  "/api/git/status": ["get"] as const,
  "/api/git/diff": ["get"] as const,
  "/api/git/commit": ["post"] as const,
  "/api/git/pull": ["post"] as const,
  "/api/git/push": ["post"] as const,
  "/api/tasks": ["get"] as const,
  "/api/scheduled": ["get","post"] as const,
  "/api/scheduled/:id": ["get","put","delete"] as const,
  "/api/scheduled/:id/pause": ["post"] as const,
  "/api/scheduled/:id/resume": ["post"] as const,
  "/api/scheduled/:id/trigger": ["post"] as const,
  "/api/sites": ["get","post"] as const,
  "/api/sites/:id/preview": ["get"] as const,
  "/api/sites/:id/publish": ["post"] as const,
  "/api/sites/:id": ["put","delete"] as const,
  "/api/worker/jobs": ["get","post"] as const,
  "/api/worker/jobs/:job_id": ["get"] as const,
  "/api/worker/jobs/:job_id/retry": ["post"] as const,
  "/api/worker/status": ["get"] as const,
  "/api/permissions": ["get"] as const,
  "/api/permissions/audit": ["get"] as const,
  "/api/permissions/scopes": ["get"] as const,
  "/api/permissions/:permission": ["put"] as const,
  "/api/tools": ["get"] as const,
  "/api/memory": ["get","post"] as const,
  "/api/memory/export": ["get"] as const,
  "/api/memory/import": ["post"] as const,
  "/api/memory/:id": ["get","patch","post","delete"] as const,
  "/api/metrics": ["get"] as const,
  "/api/metrics/history": ["get"] as const,
  "/metrics": ["get"] as const,
  "/api/plugins": ["get"] as const,
  "/api/plugins/catalog": ["get"] as const,
  "/api/plugins/install": ["post"] as const,
  "/api/plugins/update": ["post"] as const,
  "/api/plugins/uninstall": ["post"] as const,
  "/api/plugins/:name/skills": ["get"] as const,
  "/api/mcp/servers": ["get","put"] as const,
  "/ws/:session_id": ["get"] as const,
} as const;

export type OpenApiPath = keyof typeof openApiPaths;
export type OpenApiMethod<Path extends OpenApiPath> = (typeof openApiPaths)[Path][number];
