<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableMsixTooling>false</EnableMsixTooling>
    <AppxGeneratePriEnabled>false</AppxGeneratePriEnabled>
    <NoWarn>$(NoWarn);PRI257;PRI263</NoWarn>
    <DefaultLanguage>en-US</DefaultLanguage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.8.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.8.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EvoHime.Desktop\EvoHime.Desktop.csproj" />
  </ItemGroup>
</Project>
