[package]
name = "evohime-core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "evohime-core"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
evohime-model-gateway = { path = "../model-gateway" }
futures-util = "0.3"
thiserror = "2"
