#![cfg_attr(
    not(test),
    deny(clippy::unwrap_used, clippy::expect_used, clippy::panic)
)]
#![deny(missing_docs)]
//! Bounded protobuf framing for the listener named-pipe protocol.
//!
//! This crate serializes envelopes only; authentication and listener lifecycle
//! are owned by the supervisor/Core handshake.

/// Generated protobuf messages for the listener IPC contract.
#[allow(missing_docs)] // Generated by prost from the canonical listener proto.
pub mod generated {
    include!(concat!(env!("OUT_DIR"), "/evohime.listener.rs"));
}
use prost::Message;
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};
/// Maximum encoded protobuf envelope size accepted by this transport.
pub const MAX_FRAME_BYTES: usize = 256 * 1024;
/// Framing, I/O, or protobuf decoding failure.
#[derive(Debug, thiserror::Error)]
pub enum FrameError {
    /// The length prefix or encoded message exceeds [`MAX_FRAME_BYTES`].
    #[error("frame is too large")]
    TooLarge,
    /// The frame prefix or declared body could not be read in full.
    #[error("truncated frame")]
    Truncated,
    /// The underlying async stream returned an I/O error.
    #[error("I/O: {0}")]
    Io(String),
    /// The frame body is not a valid protobuf envelope.
    #[error("protobuf: {0}")]
    Protobuf(#[from] prost::DecodeError),
}
/// Reads one little-endian length-prefixed protobuf envelope.
///
/// Rejects frames larger than [`MAX_FRAME_BYTES`] before allocating the body.
pub async fn read_frame<R: AsyncRead + Unpin>(
    reader: &mut R,
) -> Result<generated::Envelope, FrameError> {
    let mut len = [0; 4];
    reader
        .read_exact(&mut len)
        .await
        .map_err(|_| FrameError::Truncated)?;
    let size = u32::from_le_bytes(len) as usize;
    if size > MAX_FRAME_BYTES {
        return Err(FrameError::TooLarge);
    };
    let mut data = vec![0; size];
    reader
        .read_exact(&mut data)
        .await
        .map_err(|_| FrameError::Truncated)?;
    Ok(generated::Envelope::decode(data.as_slice())?)
}
/// Encodes and writes one little-endian length-prefixed protobuf envelope.
///
/// The complete encoded body is checked against [`MAX_FRAME_BYTES`] before it
/// is written to the stream.
pub async fn write_frame<W: AsyncWrite + Unpin>(
    writer: &mut W,
    message: &generated::Envelope,
) -> Result<(), FrameError> {
    let data = message.encode_to_vec();
    if data.len() > MAX_FRAME_BYTES {
        return Err(FrameError::TooLarge);
    };
    writer
        .write_all(&(data.len() as u32).to_le_bytes())
        .await
        .map_err(|e| FrameError::Io(e.to_string()))?;
    writer
        .write_all(&data)
        .await
        .map_err(|e| FrameError::Io(e.to_string()))?;
    writer
        .flush()
        .await
        .map_err(|e| FrameError::Io(e.to_string()))?;
    Ok(())
}
/// Wraps a generated listener payload in the top-level envelope.
pub fn envelope(payload: generated::envelope::Payload) -> generated::Envelope {
    generated::Envelope {
        payload: Some(payload),
    }
}
